apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-basics
spec:
  replicas: 1
  selector:
    app: k8s-basics
  template:
    metadata:
      labels:
        app: k8s-basics
    spec:
      containers:
        - name: k8s-basics
          image: sarataha/k8s-basics:latest
          ports:
            - containerPort: 8888
              name: http
